import { useEffect, useState } from 'react'
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'firebase/auth'
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, orderBy, query, setDoc, updateDoc, where } from 'firebase/firestore'
import { auth, createDepartmentAccount, db, isFirebaseConfigured } from './firebase'

const ADMIN_EMAIL = 'admin.gov@incidentreport.com'
const errorText = error => error?.code === 'auth/configuration-not-found' ? 'Enable Firebase Authentication and Email/Password sign-in in Firebase Console.' : error?.message || 'Something went wrong.'

export default function Portal() {
  const [profile, setProfile] = useState(null); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [categories, setCategories] = useState([]); const [users, setUsers] = useState([]); const [reports, setReports] = useState([])
  useEffect(() => { if (!message) return undefined; const timer = window.setTimeout(() => setMessage(''), 3000); return () => window.clearTimeout(timer) }, [message])
  useEffect(() => { if (!error) return undefined; const timer = window.setTimeout(() => setError(''), 3000); return () => window.clearTimeout(timer) }, [error])
  useEffect(() => { if (!auth) return undefined; return onAuthStateChanged(auth, async account => { if (!account) return setProfile(null); try { const snapshot = await getDoc(doc(db, 'users', account.uid)); const data = snapshot.exists() ? snapshot.data() : {}; const admin = account.email?.toLowerCase() === ADMIN_EMAIL; if (!admin && !['System Administrator', 'Department Officer'].includes(data.role)) { await signOut(auth); return setError('This account is not authorized for the administration portal.') } setProfile({ id: account.uid, ...data, email: account.email, role: admin ? 'System Administrator' : data.role, name: data.name || 'Main Administrator' }) } catch (reason) { setError(errorText(reason)) } }) }, [])
  useEffect(() => { if (!profile) return; const load = async () => { try { const categorySnapshot = await getDocs(collection(db, 'categories')); const loadedCategories = categorySnapshot.docs.map(item => ({ id: item.id, ...item.data() })); setCategories(loadedCategories); if (profile.role === 'System Administrator') { const people = await getDocs(collection(db, 'users')); setUsers(people.docs.map(item => ({ id: item.id, ...item.data() }))) } const reportQuery = profile.role === 'System Administrator' ? query(collection(db, 'reports'), orderBy('createdAt', 'desc')) : query(collection(db, 'reports'), where('categoryId', 'in', profile.categoryIds || []), orderBy('createdAt', 'desc')); const incidents = await getDocs(reportQuery); setReports(incidents.docs.map(item => ({ id: item.id, ...item.data() }))) } catch (reason) { setError(errorText(reason)) } }; load() }, [profile])
  const login = async (email, password) => { try { await signInWithEmailAndPassword(auth, email, password); setError('') } catch (reason) { setError(errorText(reason)) } }
  if (!isFirebaseConfigured) return <PortalShell><main><div className="setup-state"><h1>Firebase setup required</h1><p>Add your Firebase project configuration before using the portal.</p></div></main></PortalShell>
  if (!profile) return <PortalShell><main><Login onLogin={login} error={error} /></main></PortalShell>
  const admin = profile.role === 'System Administrator'; const associatedCategoryIds = new Set((profile.role === 'System Administrator' ? users.filter(item => item.role === 'Department Officer').flatMap(item => item.categoryIds || []) : profile.categoryIds || []));
  const statusOrder = { 'Received': 0, 'In review': 1, 'Actioned': 2, 'Closed': 3 };
  const canTransitionStatus = (currentStatus, newStatus) => (statusOrder[newStatus] ?? -1) > (statusOrder[currentStatus] ?? -1);
  const getValidStatuses = (currentStatus) => ['Received', 'In review', 'Actioned', 'Closed'].filter(status => status === currentStatus || canTransitionStatus(currentStatus, status));
  const canEditStatus = report => { if (!report) return false; if (profile.role !== 'System Administrator') return true; if (!report.categoryId) return true; return !associatedCategoryIds.has(report.categoryId); };
  const updateStatus = async (reportId, status) => { try { const target = reports.find(item => item.id === reportId); if (!target || !canEditStatus(target)) return setError('You can only update reports within your own assigned category.'); if (!canTransitionStatus(target.status, status)) return setError(`Cannot change status from ${target.status} to ${status}. Status transitions are one-way.`); const nextTimeline = Array.isArray(target.timeline) ? [...target.timeline, { label: `Status updated to ${status}`, status, note: `Report marked as ${status}`, timestamp: new Date().toISOString() }] : [{ label: `Status updated to ${status}`, status, note: `Report marked as ${status}`, timestamp: new Date().toISOString() }]; await updateDoc(doc(db, 'reports', reportId), { status, updatedAt: new Date(), timeline: nextTimeline }); setReports(reports.map(item => item.id === reportId ? { ...item, status, timeline: nextTimeline } : item)); setMessage('Report status updated.') } catch (reason) { setError(errorText(reason)) } }
  return <PortalShell><main><Dashboard profile={profile} admin={admin} categories={categories} setCategories={setCategories} users={users} setUsers={setUsers} reports={reports} updateStatus={updateStatus} canEditStatus={canEditStatus} associatedCategoryIds={associatedCategoryIds} message={message} setMessage={setMessage} setError={setError} onLogout={() => signOut(auth)} /><div className={`toast ${message ? 'show' : ''}`} role="status">{message}</div></main></PortalShell>
}

function PortalShell({ children }) { return <><header className="topbar"><button className="brand" onClick={() => window.location.reload()} aria-label="CivicAlert administration"><span className="brand-mark">+</span><span>Civic<span>Alert</span></span></button><span className="portal-label">Administration portal</span></header>{children}</> }
function Login({ onLogin, error }) { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); return <div className="login-panel panel"><p className="eyebrow">Restricted access</p><h1>Department portal</h1><p>Sign in with the account created by the main administrator.</p><form onSubmit={event => { event.preventDefault(); onLogin(email, password) }}><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} required /></label><button className="primary-button" type="submit">Sign in <span>→</span></button>{error && <p className="location-error">{error}</p>}</form></div> }

function Dashboard({ profile, admin, categories, setCategories, users, setUsers, reports, updateStatus, canEditStatus, associatedCategoryIds, message, setMessage, setError, onLogout }) { const [page, setPage] = useState('reports'); const [selected, setSelected] = useState(null); const statusOrder = { 'Received': 0, 'In review': 1, 'Actioned': 2, 'Closed': 3 }; const canTransitionStatus = (currentStatus, newStatus) => (statusOrder[newStatus] ?? -1) > (statusOrder[currentStatus] ?? -1); const getValidStatuses = (currentStatus) => ['Received', 'In review', 'Actioned', 'Closed'].filter(status => status === currentStatus || canTransitionStatus(currentStatus, status)); return <><div className="dashboard-head"><div><p className="eyebrow">{admin ? 'System administration' : 'Department workspace'}</p><h1>Good day, {profile.name.split(' ')[0]}.</h1></div><div className="user-chip">{profile.email} · <button className="logout" onClick={onLogout}>Sign out</button></div></div>{admin && <nav className="admin-tabs" aria-label="Admin sections"><button className={page === 'reports' ? 'active' : ''} onClick={() => setPage('reports')}>Reports <span>{reports.length}</span></button><button className={page === 'categories' ? 'active' : ''} onClick={() => setPage('categories')}>Categories <span>{categories.length}</span></button><button className={page === 'users' ? 'active' : ''} onClick={() => setPage('users')}>Users <span>{users.filter(item => item.role !== 'System Administrator').length}</span></button></nav>}{page === 'reports' && <ReportsPage reports={reports} updateStatus={updateStatus} onSelect={setSelected} admin={admin} canEditStatus={canEditStatus} associatedCategoryIds={associatedCategoryIds} getValidStatuses={getValidStatuses} />}{page === 'categories' && <CategoriesPage categories={categories} setCategories={setCategories} setMessage={setMessage} setError={setError} />}{page === 'users' && <UsersPage categories={categories} users={users} setUsers={setUsers} setMessage={setMessage} setError={setError} />}{selected && <ReportDialog report={selected} onClose={() => setSelected(null)} updateStatus={updateStatus} canEditStatus={canEditStatus} getValidStatuses={getValidStatuses} />}</> }

function ReportsPage({ reports, updateStatus, onSelect, admin, canEditStatus, associatedCategoryIds, getValidStatuses }) {
  const mapsUrlFor = report => report.mapsUrl || (report.latitude !== undefined && report.latitude !== null && report.longitude !== undefined && report.longitude !== null ? `https://www.google.com/maps?q=${Number(report.latitude)},${Number(report.longitude)}` : report.location ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(report.location)}` : '');
  const timelineEvents = report => Array.isArray(report?.timeline) && report.timeline.length ? report.timeline.slice(-3) : [{ label: 'Report submitted', status: report?.status || 'Received', note: 'Report received in the system' }];
  const formatReportDate = value => {
    if (!value) return '—';
    const when = value?.toDate ? value.toDate() : new Date(value);
    if (Number.isNaN(when.getTime())) return '—';
    return when.toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
  };
  return <section><div className="dashboard-grid"><div className="stat"><small>Visible reports</small><strong>{reports.length}</strong></div><div className="stat"><small>Needs attention</small><strong>{reports.filter(item => item.status === 'Received').length}</strong></div><div className="stat"><small>Access scope</small><strong>{admin ? 'All' : 'Assigned'}</strong></div></div><div className="dashboard-table"><div className="table-title">{admin ? 'All routed reports' : 'Reports for your categories'}</div>{reports.length ? <table><thead><tr><th>Reference</th><th>Issue</th><th>Category</th><th>Priority</th><th>Date</th><th>Status</th></tr></thead><tbody>{reports.map(item => { const priority = (item.priority === 'Urgent' ? 'Critical' : (item.priority || 'Normal')); const priorityClass = priority.toLowerCase().replace(/\s+/g, '-'); const locationUrl = mapsUrlFor(item); const issueLocation = locationUrl ? <a className="map-link" href={locationUrl} target="_blank" rel="noreferrer" onClick={event => event.stopPropagation()}>{item.location}</a> : <span>{item.location}</span>; return <tr key={item.id} className={`clickable-row ${associatedCategoryIds.has(item.categoryId) ? 'associated-row' : ''}`} onClick={() => onSelect(item)}><td>{item.reference}</td><td><strong>{item.title}</strong><br />{issueLocation}<div className="timeline-inline">{timelineEvents(item).map((event, index) => <div className="timeline-inline-item" key={`${item.id}-timeline-${index}`}><span className="timeline-inline-dot" /><span>{event.label || event.status || 'Update'}</span></div>)}</div></td><td>{item.category}</td><td><span className={`priority ${priorityClass}`}>{priority}</span></td><td>{formatReportDate(item.createdAt || item.submittedAt)}</td><td onClick={event => event.stopPropagation()}><select className="status-select" value={item.status} onChange={event => updateStatus(item.id, event.target.value)} disabled={!canEditStatus(item)}>{getValidStatuses(item.status).map(status => <option key={status}>{status}</option>)}</select></td></tr> })}</tbody></table> : <div className="empty-state">No reports are assigned to your categories.</div>}</div></section> }

function ReportDialog({ report, onClose, updateStatus, canEditStatus, getValidStatuses }) {
  const locationUrl = report.mapsUrl || (report.latitude !== undefined && report.latitude !== null && report.longitude !== undefined && report.longitude !== null ? `https://www.google.com/maps?q=${Number(report.latitude)},${Number(report.longitude)}` : report.location ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(report.location)}` : '');
  const timelineEvents = Array.isArray(report.timeline) && report.timeline.length ? report.timeline.slice(-5) : [{ label: 'Report submitted', status: report.status || 'Received', note: 'Report received in the system' }];
  return <div className="dialog-backdrop" onClick={onClose}><div className="report-dialog" role="dialog" aria-modal="true" onClick={event => event.stopPropagation()}><button className="dialog-close" onClick={onClose} aria-label="Close">×</button><p className="eyebrow">Report details</p><h2>{report.title}</h2><div className="detail-grid"><div><small>Reference</small><strong>{report.reference}</strong></div><div><small>Category</small><strong>{report.category}</strong></div><div><small>Priority</small><strong>{report.priority}</strong></div><div><small>Status</small><select className="status-select" value={report.status} onChange={event => updateStatus(report.id, event.target.value)} disabled={!canEditStatus(report)}>{getValidStatuses(report.status).map(status => <option key={status}>{status}</option>)}</select></div><div className="detail-wide"><small>Location</small>{locationUrl ? <a className="map-link location-link" href={locationUrl} target="_blank" rel="noreferrer"><strong>{report.location}</strong></a> : <strong>{report.location}</strong>}{locationUrl && <a className="map-link" href={locationUrl} target="_blank" rel="noreferrer">Open exact location in Google Maps ↗</a>}</div><div className="detail-wide"><small>Description</small><p>{report.description}</p></div><div><small>Reporter</small><strong>{report.reporter || 'Anonymous'}</strong></div><div><small>Contact email</small><strong>{report.email || 'Not provided'}</strong></div><div><small>Phone</small><strong>{report.phone || 'Not provided'}</strong></div>{report.latitude && <div><small>GPS accuracy</small><strong>{report.accuracy ? `${report.accuracy}m` : 'Coordinate captured'}</strong></div>}</div>{report.evidence?.length > 0 && <div className="dialog-evidence"><small>Evidence photos</small><div className="photo-grid">{report.evidence.map(photo => <a href={photo.url} target="_blank" rel="noreferrer" key={photo.url}><img src={photo.url} alt={photo.name || 'Evidence'} /></a>)}</div></div>}<div className="report-timeline"><strong>Timeline</strong>{timelineEvents.map((event, index) => <div className="timeline-item" key={`${report.id}-dialog-${index}`}><span className="timeline-dot" /><div><strong>{event.label || event.status || 'Update'}</strong><small>{event.note || 'Updated'}</small></div></div>)}</div></div></div> }

function CategoriesPage({ categories, setCategories, setMessage, setError }) { const [selected, setSelected] = useState(categories[0]?.id || ''); const category = categories.find(item => item.id === selected); const [email, setEmail] = useState(category?.email || ''); useEffect(() => setEmail(category?.email || ''), [category]); const add = async event => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = data.get('name')?.toString().trim(); const notificationEmail = data.get('email')?.toString().trim(); if (!name || !notificationEmail) return setError('Enter a category name and notification email.'); try { const saved = await addDoc(collection(db, 'categories'), { name, email: notificationEmail, createdAt: new Date() }); setCategories([...categories, { id: saved.id, name, email: notificationEmail }]); setSelected(saved.id); setEmail(notificationEmail); event.currentTarget.reset(); setMessage('Category added.') } catch (reason) { setError(errorText(reason)) } }; const save = async event => { event.preventDefault(); if (!selected) return; await updateDoc(doc(db, 'categories', selected), { email }); setCategories(categories.map(item => item.id === selected ? { ...item, email } : item)); setMessage('Routing email updated.') }; return <section className="admin-page"><div className="page-heading"><div><p className="eyebrow">Department setup</p><h2>Categories</h2></div></div><div className="admin-card"><h3>Add category</h3><form onSubmit={add}><label>Department name<input name="name" required placeholder="e.g. Roads and Transport" /></label><label>Notification email<input name="email" type="email" required placeholder="roads@your-domain.gov" /></label><button className="outline-button" type="submit">+ Add category</button></form><h3 className="admin-label">Edit routing</h3><form onSubmit={save}><label>Category<select value={selected} onChange={event => setSelected(event.target.value)} disabled={!categories.length}><option value="">{categories.length ? 'Select category' : 'No categories yet'}</option>{categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Notification email<input type="email" value={email} onChange={event => setEmail(event.target.value)} disabled={!category} required /></label><button className="primary-button" type="submit" disabled={!category}>Save routing <span>→</span></button></form></div></section> }

function UsersPage({ categories, users, setUsers, setMessage, setError }) { 
  const [editingUser, setEditingUser] = useState(null);
  const [editEmail, setEditEmail] = useState('');
  
  const add = async event => { 
    event.preventDefault(); 
    const data = new FormData(event.currentTarget); 
    try { 
      const email = data.get('email').toString().trim().toLowerCase(); 
      const uid = await createDepartmentAccount(email, data.get('password')); 
      const user = { name: data.get('name'), email, role: 'Department Officer', categoryIds: [data.get('categoryId')] }; 
      await setDoc(doc(db, 'users', uid), user); 
      setUsers([...users, { id: uid, ...user }]); 
      event.currentTarget.reset(); 
      setMessage('Department account created.') 
    } catch (reason) { setError(errorText(reason)) } 
  };
  
  const startEdit = (user) => {
    setEditingUser(user.id);
    setEditEmail(user.email);
  };
  
  const cancelEdit = () => {
    setEditingUser(null);
    setEditEmail('');
  };
  
  const saveEmail = async (userId) => {
    try {
      await updateDoc(doc(db, 'users', userId), { email: editEmail.toLowerCase() });
      setUsers(users.map(user => user.id === userId ? { ...user, email: editEmail.toLowerCase() } : user));
      setMessage('User email updated successfully.');
      cancelEdit();
    } catch (reason) {
      setError(errorText(reason));
    }
  };
  
  const deleteUser = async (userId) => {
    if (!confirm('Are you sure you want to delete this user?')) return;
    try {
      await deleteDoc(doc(db, 'users', userId));
      setUsers(users.filter(user => user.id !== userId));
      setMessage('User deleted successfully.');
    } catch (reason) {
      setError(errorText(reason));
    }
  };
  
  return <section className="admin-page"><div className="page-heading"><div><p className="eyebrow">Access management</p><h2>Users</h2></div></div><div className="admin-card"><h3>Create department account</h3><p className="field-hint">Each user receives access only to the selected category.</p><form onSubmit={add}><label>User name<input name="name" required /></label><label>Email<input name="email" type="email" required /></label><label>Temporary password<input name="password" type="password" minLength="6" required /></label><label>Assign category<select name="categoryId" required disabled={!categories.length}>{categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="primary-button" type="submit" disabled={!categories.length}>+ Create account</button></form></div><div className="admin-card"><h3>Authorized users</h3>{users.filter(item => item.role !== 'System Administrator').map(item => <div className="user-row" key={item.id}><span className="user-name">{item.name}</span><div className="user-email-section">{editingUser === item.id ? <div className="edit-email-group"><input type="email" value={editEmail} onChange={e => setEditEmail(e.target.value)} className="edit-email-input" /><button className="small-button" onClick={() => saveEmail(item.id)}>✓</button><button className="text-button" onClick={cancelEdit}>✕</button></div> : <><small>{item.email}</small></>}</div><small className="user-category">{(item.categoryIds || []).map(id => categories.find(cat => cat.id === id)?.name || id).join(', ')}</small><div className="user-email-actions"><button className="icon-button" onClick={() => startEdit(item)} aria-label="Edit email">✎</button><button className="icon-button danger-button" onClick={() => deleteUser(item.id)} aria-label="Delete user">🗑</button></div></div>)}</div></section> }
